// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module k2c_dense_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        output_numel_read,
        input_array_address0,
        input_array_ce0,
        input_array_q0,
        input_array8_address0,
        input_array8_ce0,
        input_array8_q0,
        input_array9_address0,
        input_array9_ce0,
        input_array9_q0,
        input_array10_address0,
        input_array10_ce0,
        input_array10_q0,
        input_array11_address0,
        input_array11_ce0,
        input_array11_q0,
        input_array12_address0,
        input_array12_ce0,
        input_array12_q0,
        input_array13_address0,
        input_array13_ce0,
        input_array13_q0,
        input_array14_address0,
        input_array14_ce0,
        input_array14_q0,
        input_dim,
        input_numel_read,
        input_shape_address0,
        input_shape_ce0,
        input_shape_q0,
        kernel_dim,
        dense_13_output_arra_7_address0,
        dense_13_output_arra_7_ce0,
        dense_13_output_arra_7_we0,
        dense_13_output_arra_7_d0,
        dense_13_output_arra_7_q0,
        dense_13_output_arra_6_address0,
        dense_13_output_arra_6_ce0,
        dense_13_output_arra_6_we0,
        dense_13_output_arra_6_d0,
        dense_13_output_arra_6_q0,
        dense_13_output_arra_5_address0,
        dense_13_output_arra_5_ce0,
        dense_13_output_arra_5_we0,
        dense_13_output_arra_5_d0,
        dense_13_output_arra_5_q0,
        dense_13_output_arra_4_address0,
        dense_13_output_arra_4_ce0,
        dense_13_output_arra_4_we0,
        dense_13_output_arra_4_d0,
        dense_13_output_arra_4_q0,
        dense_13_output_arra_3_address0,
        dense_13_output_arra_3_ce0,
        dense_13_output_arra_3_we0,
        dense_13_output_arra_3_d0,
        dense_13_output_arra_3_q0,
        dense_13_output_arra_2_address0,
        dense_13_output_arra_2_ce0,
        dense_13_output_arra_2_we0,
        dense_13_output_arra_2_d0,
        dense_13_output_arra_2_q0,
        dense_13_output_arra_1_address0,
        dense_13_output_arra_1_ce0,
        dense_13_output_arra_1_we0,
        dense_13_output_arra_1_d0,
        dense_13_output_arra_1_q0,
        dense_13_output_arra_address0,
        dense_13_output_arra_ce0,
        dense_13_output_arra_we0,
        dense_13_output_arra_d0,
        dense_13_output_arra_q0
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] output_numel_read;
output  [3:0] input_array_address0;
output   input_array_ce0;
input  [31:0] input_array_q0;
output  [3:0] input_array8_address0;
output   input_array8_ce0;
input  [31:0] input_array8_q0;
output  [3:0] input_array9_address0;
output   input_array9_ce0;
input  [31:0] input_array9_q0;
output  [3:0] input_array10_address0;
output   input_array10_ce0;
input  [31:0] input_array10_q0;
output  [3:0] input_array11_address0;
output   input_array11_ce0;
input  [31:0] input_array11_q0;
output  [3:0] input_array12_address0;
output   input_array12_ce0;
input  [31:0] input_array12_q0;
output  [3:0] input_array13_address0;
output   input_array13_ce0;
input  [31:0] input_array13_q0;
output  [3:0] input_array14_address0;
output   input_array14_ce0;
input  [31:0] input_array14_q0;
input  [63:0] input_dim;
input  [63:0] input_numel_read;
output  [2:0] input_shape_address0;
output   input_shape_ce0;
input  [63:0] input_shape_q0;
input  [63:0] kernel_dim;
output  [3:0] dense_13_output_arra_7_address0;
output   dense_13_output_arra_7_ce0;
output   dense_13_output_arra_7_we0;
output  [31:0] dense_13_output_arra_7_d0;
input  [31:0] dense_13_output_arra_7_q0;
output  [3:0] dense_13_output_arra_6_address0;
output   dense_13_output_arra_6_ce0;
output   dense_13_output_arra_6_we0;
output  [31:0] dense_13_output_arra_6_d0;
input  [31:0] dense_13_output_arra_6_q0;
output  [3:0] dense_13_output_arra_5_address0;
output   dense_13_output_arra_5_ce0;
output   dense_13_output_arra_5_we0;
output  [31:0] dense_13_output_arra_5_d0;
input  [31:0] dense_13_output_arra_5_q0;
output  [3:0] dense_13_output_arra_4_address0;
output   dense_13_output_arra_4_ce0;
output   dense_13_output_arra_4_we0;
output  [31:0] dense_13_output_arra_4_d0;
input  [31:0] dense_13_output_arra_4_q0;
output  [3:0] dense_13_output_arra_3_address0;
output   dense_13_output_arra_3_ce0;
output   dense_13_output_arra_3_we0;
output  [31:0] dense_13_output_arra_3_d0;
input  [31:0] dense_13_output_arra_3_q0;
output  [3:0] dense_13_output_arra_2_address0;
output   dense_13_output_arra_2_ce0;
output   dense_13_output_arra_2_we0;
output  [31:0] dense_13_output_arra_2_d0;
input  [31:0] dense_13_output_arra_2_q0;
output  [3:0] dense_13_output_arra_1_address0;
output   dense_13_output_arra_1_ce0;
output   dense_13_output_arra_1_we0;
output  [31:0] dense_13_output_arra_1_d0;
input  [31:0] dense_13_output_arra_1_q0;
output  [3:0] dense_13_output_arra_address0;
output   dense_13_output_arra_ce0;
output   dense_13_output_arra_we0;
output  [31:0] dense_13_output_arra_d0;
input  [31:0] dense_13_output_arra_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] input_array_address0;
reg input_array_ce0;
reg[3:0] input_array8_address0;
reg input_array8_ce0;
reg[3:0] input_array9_address0;
reg input_array9_ce0;
reg[3:0] input_array10_address0;
reg input_array10_ce0;
reg[3:0] input_array11_address0;
reg input_array11_ce0;
reg[3:0] input_array12_address0;
reg input_array12_ce0;
reg[3:0] input_array13_address0;
reg input_array13_ce0;
reg[3:0] input_array14_address0;
reg input_array14_ce0;
reg[2:0] input_shape_address0;
reg input_shape_ce0;
reg[3:0] dense_13_output_arra_7_address0;
reg dense_13_output_arra_7_ce0;
reg dense_13_output_arra_7_we0;
reg[31:0] dense_13_output_arra_7_d0;
reg[3:0] dense_13_output_arra_6_address0;
reg dense_13_output_arra_6_ce0;
reg dense_13_output_arra_6_we0;
reg[31:0] dense_13_output_arra_6_d0;
reg[3:0] dense_13_output_arra_5_address0;
reg dense_13_output_arra_5_ce0;
reg dense_13_output_arra_5_we0;
reg[31:0] dense_13_output_arra_5_d0;
reg[3:0] dense_13_output_arra_4_address0;
reg dense_13_output_arra_4_ce0;
reg dense_13_output_arra_4_we0;
reg[31:0] dense_13_output_arra_4_d0;
reg[3:0] dense_13_output_arra_3_address0;
reg dense_13_output_arra_3_ce0;
reg dense_13_output_arra_3_we0;
reg[31:0] dense_13_output_arra_3_d0;
reg[3:0] dense_13_output_arra_2_address0;
reg dense_13_output_arra_2_ce0;
reg dense_13_output_arra_2_we0;
reg[31:0] dense_13_output_arra_2_d0;
reg[3:0] dense_13_output_arra_1_address0;
reg dense_13_output_arra_1_ce0;
reg dense_13_output_arra_1_we0;
reg[31:0] dense_13_output_arra_1_d0;
reg[3:0] dense_13_output_arra_address0;
reg dense_13_output_arra_ce0;
reg dense_13_output_arra_we0;
reg[31:0] dense_13_output_arra_d0;

(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [6:0] dense_13_bias_array_address0;
reg    dense_13_bias_array_ce0;
wire   [31:0] dense_13_bias_array_q0;
reg   [63:0] dense_13_kernel_nume;
reg   [63:0] dense_13_bias_numel;
wire   [0:0] tmp_fu_514_p2;
reg   [0:0] tmp_reg_792;
wire   [63:0] tmp_14_fu_520_p2;
reg   [63:0] tmp_14_reg_796;
wire   [0:0] icmp_fu_542_p2;
reg   [0:0] icmp_reg_806;
wire    ap_CS_fsm_state3;
wire   [63:0] i_28_fu_558_p2;
reg   [63:0] i_28_reg_819;
wire    ap_CS_fsm_state5;
wire   [2:0] tmp_71_fu_564_p1;
reg   [2:0] tmp_71_reg_824;
wire   [0:0] exitcond4_fu_553_p2;
reg   [3:0] dense_13_output_arra_24_reg_829;
reg   [3:0] dense_13_output_arra_25_reg_834;
reg   [3:0] dense_13_output_arra_26_reg_839;
reg   [3:0] dense_13_output_arra_27_reg_844;
reg   [3:0] dense_13_output_arra_28_reg_849;
reg   [3:0] dense_13_output_arra_29_reg_854;
reg   [3:0] dense_13_output_arra_30_reg_859;
reg   [3:0] dense_13_output_arra_31_reg_864;
wire   [31:0] tmp_28_fu_593_p10;
reg   [31:0] tmp_28_reg_869;
wire    ap_CS_fsm_state6;
wire   [0:0] notlhs_fu_632_p2;
reg   [0:0] notlhs_reg_875;
wire    ap_CS_fsm_state7;
wire   [0:0] notrhs_fu_638_p2;
reg   [0:0] notrhs_reg_880;
wire   [0:0] grp_fu_509_p2;
reg   [0:0] tmp_31_reg_885;
wire    ap_CS_fsm_state8;
wire   [63:0] outrows1_fu_653_p3;
reg   [63:0] outrows1_reg_893;
wire    ap_CS_fsm_state10;
wire   [63:0] tmp_68_fu_661_p2;
reg   [63:0] tmp_68_reg_899;
wire    ap_CS_fsm_state11;
wire    grp_k2c_affine_matmul_fu_430_ap_idle;
wire    grp_k2c_affine_matmul_fu_430_ap_ready;
wire    grp_k2c_affine_matmul_fu_430_ap_done;
wire   [63:0] i_29_fu_671_p2;
reg   [63:0] i_29_reg_907;
wire    ap_CS_fsm_state12;
wire   [2:0] tmp_69_fu_677_p1;
reg   [2:0] tmp_69_reg_912;
wire   [0:0] exitcond1_fu_666_p2;
reg   [3:0] dense_13_output_arra_8_reg_917;
reg   [3:0] dense_13_output_arra_9_reg_922;
reg   [3:0] dense_13_output_arra_10_reg_927;
reg   [3:0] dense_13_output_arra_11_reg_932;
reg   [3:0] dense_13_output_arra_12_reg_937;
reg   [3:0] dense_13_output_arra_13_reg_942;
reg   [3:0] dense_13_output_arra_14_reg_947;
reg   [3:0] dense_13_output_arra_15_reg_952;
wire   [31:0] tmp_s_fu_706_p10;
reg   [31:0] tmp_s_reg_957;
wire    ap_CS_fsm_state13;
wire   [0:0] notlhs4_fu_745_p2;
reg   [0:0] notlhs4_reg_963;
wire    ap_CS_fsm_state14;
wire   [0:0] notrhs5_fu_751_p2;
reg   [0:0] notrhs5_reg_968;
reg   [0:0] tmp_26_reg_973;
wire    ap_CS_fsm_state15;
wire   [0:0] tmp_27_fu_761_p2;
wire    ap_CS_fsm_state16;
wire    grp_k2c_dot_fu_364_ap_start;
wire    grp_k2c_dot_fu_364_ap_done;
wire    grp_k2c_dot_fu_364_ap_idle;
wire    grp_k2c_dot_fu_364_ap_ready;
wire   [3:0] grp_k2c_dot_fu_364_C_array_0_address0;
wire    grp_k2c_dot_fu_364_C_array_0_ce0;
wire    grp_k2c_dot_fu_364_C_array_0_we0;
wire   [31:0] grp_k2c_dot_fu_364_C_array_0_d0;
wire   [3:0] grp_k2c_dot_fu_364_C_array_1_address0;
wire    grp_k2c_dot_fu_364_C_array_1_ce0;
wire    grp_k2c_dot_fu_364_C_array_1_we0;
wire   [31:0] grp_k2c_dot_fu_364_C_array_1_d0;
wire   [3:0] grp_k2c_dot_fu_364_C_array_2_address0;
wire    grp_k2c_dot_fu_364_C_array_2_ce0;
wire    grp_k2c_dot_fu_364_C_array_2_we0;
wire   [31:0] grp_k2c_dot_fu_364_C_array_2_d0;
wire   [3:0] grp_k2c_dot_fu_364_C_array_3_address0;
wire    grp_k2c_dot_fu_364_C_array_3_ce0;
wire    grp_k2c_dot_fu_364_C_array_3_we0;
wire   [31:0] grp_k2c_dot_fu_364_C_array_3_d0;
wire   [3:0] grp_k2c_dot_fu_364_C_array_4_address0;
wire    grp_k2c_dot_fu_364_C_array_4_ce0;
wire    grp_k2c_dot_fu_364_C_array_4_we0;
wire   [31:0] grp_k2c_dot_fu_364_C_array_4_d0;
wire   [3:0] grp_k2c_dot_fu_364_C_array_5_address0;
wire    grp_k2c_dot_fu_364_C_array_5_ce0;
wire    grp_k2c_dot_fu_364_C_array_5_we0;
wire   [31:0] grp_k2c_dot_fu_364_C_array_5_d0;
wire   [3:0] grp_k2c_dot_fu_364_C_array_6_address0;
wire    grp_k2c_dot_fu_364_C_array_6_ce0;
wire    grp_k2c_dot_fu_364_C_array_6_we0;
wire   [31:0] grp_k2c_dot_fu_364_C_array_6_d0;
wire   [3:0] grp_k2c_dot_fu_364_C_array_7_address0;
wire    grp_k2c_dot_fu_364_C_array_7_ce0;
wire    grp_k2c_dot_fu_364_C_array_7_we0;
wire   [31:0] grp_k2c_dot_fu_364_C_array_7_d0;
wire   [3:0] grp_k2c_dot_fu_364_A_array_0_address0;
wire    grp_k2c_dot_fu_364_A_array_0_ce0;
wire   [3:0] grp_k2c_dot_fu_364_A_array_1_address0;
wire    grp_k2c_dot_fu_364_A_array_1_ce0;
wire   [3:0] grp_k2c_dot_fu_364_A_array_2_address0;
wire    grp_k2c_dot_fu_364_A_array_2_ce0;
wire   [3:0] grp_k2c_dot_fu_364_A_array_3_address0;
wire    grp_k2c_dot_fu_364_A_array_3_ce0;
wire   [3:0] grp_k2c_dot_fu_364_A_array_4_address0;
wire    grp_k2c_dot_fu_364_A_array_4_ce0;
wire   [3:0] grp_k2c_dot_fu_364_A_array_5_address0;
wire    grp_k2c_dot_fu_364_A_array_5_ce0;
wire   [3:0] grp_k2c_dot_fu_364_A_array_6_address0;
wire    grp_k2c_dot_fu_364_A_array_6_ce0;
wire   [3:0] grp_k2c_dot_fu_364_A_array_7_address0;
wire    grp_k2c_dot_fu_364_A_array_7_ce0;
wire   [2:0] grp_k2c_dot_fu_364_A_shape_address0;
wire    grp_k2c_dot_fu_364_A_shape_ce0;
wire    grp_k2c_affine_matmul_fu_430_ap_start;
wire   [3:0] grp_k2c_affine_matmul_fu_430_C_0_address0;
wire    grp_k2c_affine_matmul_fu_430_C_0_ce0;
wire    grp_k2c_affine_matmul_fu_430_C_0_we0;
wire   [31:0] grp_k2c_affine_matmul_fu_430_C_0_d0;
wire   [3:0] grp_k2c_affine_matmul_fu_430_C_1_address0;
wire    grp_k2c_affine_matmul_fu_430_C_1_ce0;
wire    grp_k2c_affine_matmul_fu_430_C_1_we0;
wire   [31:0] grp_k2c_affine_matmul_fu_430_C_1_d0;
wire   [3:0] grp_k2c_affine_matmul_fu_430_C_2_address0;
wire    grp_k2c_affine_matmul_fu_430_C_2_ce0;
wire    grp_k2c_affine_matmul_fu_430_C_2_we0;
wire   [31:0] grp_k2c_affine_matmul_fu_430_C_2_d0;
wire   [3:0] grp_k2c_affine_matmul_fu_430_C_3_address0;
wire    grp_k2c_affine_matmul_fu_430_C_3_ce0;
wire    grp_k2c_affine_matmul_fu_430_C_3_we0;
wire   [31:0] grp_k2c_affine_matmul_fu_430_C_3_d0;
wire   [3:0] grp_k2c_affine_matmul_fu_430_C_4_address0;
wire    grp_k2c_affine_matmul_fu_430_C_4_ce0;
wire    grp_k2c_affine_matmul_fu_430_C_4_we0;
wire   [31:0] grp_k2c_affine_matmul_fu_430_C_4_d0;
wire   [3:0] grp_k2c_affine_matmul_fu_430_C_5_address0;
wire    grp_k2c_affine_matmul_fu_430_C_5_ce0;
wire    grp_k2c_affine_matmul_fu_430_C_5_we0;
wire   [31:0] grp_k2c_affine_matmul_fu_430_C_5_d0;
wire   [3:0] grp_k2c_affine_matmul_fu_430_C_6_address0;
wire    grp_k2c_affine_matmul_fu_430_C_6_ce0;
wire    grp_k2c_affine_matmul_fu_430_C_6_we0;
wire   [31:0] grp_k2c_affine_matmul_fu_430_C_6_d0;
wire   [3:0] grp_k2c_affine_matmul_fu_430_C_7_address0;
wire    grp_k2c_affine_matmul_fu_430_C_7_ce0;
wire    grp_k2c_affine_matmul_fu_430_C_7_we0;
wire   [31:0] grp_k2c_affine_matmul_fu_430_C_7_d0;
wire   [3:0] grp_k2c_affine_matmul_fu_430_A_0_address0;
wire    grp_k2c_affine_matmul_fu_430_A_0_ce0;
wire   [3:0] grp_k2c_affine_matmul_fu_430_A_1_address0;
wire    grp_k2c_affine_matmul_fu_430_A_1_ce0;
wire   [3:0] grp_k2c_affine_matmul_fu_430_A_2_address0;
wire    grp_k2c_affine_matmul_fu_430_A_2_ce0;
wire   [3:0] grp_k2c_affine_matmul_fu_430_A_3_address0;
wire    grp_k2c_affine_matmul_fu_430_A_3_ce0;
wire   [3:0] grp_k2c_affine_matmul_fu_430_A_4_address0;
wire    grp_k2c_affine_matmul_fu_430_A_4_ce0;
wire   [3:0] grp_k2c_affine_matmul_fu_430_A_5_address0;
wire    grp_k2c_affine_matmul_fu_430_A_5_ce0;
wire   [3:0] grp_k2c_affine_matmul_fu_430_A_6_address0;
wire    grp_k2c_affine_matmul_fu_430_A_6_ce0;
wire   [3:0] grp_k2c_affine_matmul_fu_430_A_7_address0;
wire    grp_k2c_affine_matmul_fu_430_A_7_ce0;
wire   [6:0] grp_k2c_affine_matmul_fu_430_d_address0;
wire    grp_k2c_affine_matmul_fu_430_d_ce0;
wire    grp_k2c_bias_add_fu_485_ap_start;
wire    grp_k2c_bias_add_fu_485_ap_done;
wire    grp_k2c_bias_add_fu_485_ap_idle;
wire    grp_k2c_bias_add_fu_485_ap_ready;
wire   [3:0] grp_k2c_bias_add_fu_485_A_array_0_address0;
wire    grp_k2c_bias_add_fu_485_A_array_0_ce0;
wire    grp_k2c_bias_add_fu_485_A_array_0_we0;
wire   [31:0] grp_k2c_bias_add_fu_485_A_array_0_d0;
wire   [3:0] grp_k2c_bias_add_fu_485_A_array_1_address0;
wire    grp_k2c_bias_add_fu_485_A_array_1_ce0;
wire    grp_k2c_bias_add_fu_485_A_array_1_we0;
wire   [31:0] grp_k2c_bias_add_fu_485_A_array_1_d0;
wire   [3:0] grp_k2c_bias_add_fu_485_A_array_2_address0;
wire    grp_k2c_bias_add_fu_485_A_array_2_ce0;
wire    grp_k2c_bias_add_fu_485_A_array_2_we0;
wire   [31:0] grp_k2c_bias_add_fu_485_A_array_2_d0;
wire   [3:0] grp_k2c_bias_add_fu_485_A_array_3_address0;
wire    grp_k2c_bias_add_fu_485_A_array_3_ce0;
wire    grp_k2c_bias_add_fu_485_A_array_3_we0;
wire   [31:0] grp_k2c_bias_add_fu_485_A_array_3_d0;
wire   [3:0] grp_k2c_bias_add_fu_485_A_array_4_address0;
wire    grp_k2c_bias_add_fu_485_A_array_4_ce0;
wire    grp_k2c_bias_add_fu_485_A_array_4_we0;
wire   [31:0] grp_k2c_bias_add_fu_485_A_array_4_d0;
wire   [3:0] grp_k2c_bias_add_fu_485_A_array_5_address0;
wire    grp_k2c_bias_add_fu_485_A_array_5_ce0;
wire    grp_k2c_bias_add_fu_485_A_array_5_we0;
wire   [31:0] grp_k2c_bias_add_fu_485_A_array_5_d0;
wire   [3:0] grp_k2c_bias_add_fu_485_A_array_6_address0;
wire    grp_k2c_bias_add_fu_485_A_array_6_ce0;
wire    grp_k2c_bias_add_fu_485_A_array_6_we0;
wire   [31:0] grp_k2c_bias_add_fu_485_A_array_6_d0;
wire   [3:0] grp_k2c_bias_add_fu_485_A_array_7_address0;
wire    grp_k2c_bias_add_fu_485_A_array_7_ce0;
wire    grp_k2c_bias_add_fu_485_A_array_7_we0;
wire   [31:0] grp_k2c_bias_add_fu_485_A_array_7_d0;
reg   [63:0] i_2_reg_342;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state4;
reg   [63:0] i_reg_353;
wire    ap_CS_fsm_state17;
reg    grp_k2c_dot_fu_364_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_k2c_affine_matmul_fu_430_ap_start_reg;
reg    grp_k2c_bias_add_fu_485_ap_start_reg;
wire   [63:0] newIndex_cast_fu_578_p1;
wire   [63:0] newIndex2_cast_fu_691_p1;
wire   [0:0] tmp_32_fu_648_p2;
reg   [31:0] grp_fu_509_p0;
wire   [62:0] tmp_67_fu_532_p4;
wire   [5:0] newIndex_fu_568_p4;
wire   [63:0] tmp_28_fu_593_p9;
wire   [31:0] p_to_int2_fu_615_p1;
wire   [7:0] tmp_29_fu_618_p4;
wire   [22:0] tmp_72_fu_628_p1;
wire   [0:0] tmp_30_fu_644_p2;
wire   [5:0] newIndex2_fu_681_p4;
wire   [63:0] tmp_s_fu_706_p9;
wire   [31:0] p_to_int_fu_728_p1;
wire   [7:0] tmp_24_fu_731_p4;
wire   [22:0] tmp_70_fu_741_p1;
wire   [0:0] tmp_25_fu_757_p2;
reg   [16:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
#0 dense_13_kernel_nume = 64'd2560;
#0 dense_13_bias_numel = 64'd128;
#0 grp_k2c_dot_fu_364_ap_start_reg = 1'b0;
#0 grp_k2c_affine_matmul_fu_430_ap_start_reg = 1'b0;
#0 grp_k2c_bias_add_fu_485_ap_start_reg = 1'b0;
end

k2c_dense_3_denseEe0 #(
    .DataWidth( 32 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
dense_13_bias_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_13_bias_array_address0),
    .ce0(dense_13_bias_array_ce0),
    .q0(dense_13_bias_array_q0)
);

k2c_dot grp_k2c_dot_fu_364(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_k2c_dot_fu_364_ap_start),
    .ap_done(grp_k2c_dot_fu_364_ap_done),
    .ap_idle(grp_k2c_dot_fu_364_ap_idle),
    .ap_ready(grp_k2c_dot_fu_364_ap_ready),
    .C_array_0_address0(grp_k2c_dot_fu_364_C_array_0_address0),
    .C_array_0_ce0(grp_k2c_dot_fu_364_C_array_0_ce0),
    .C_array_0_we0(grp_k2c_dot_fu_364_C_array_0_we0),
    .C_array_0_d0(grp_k2c_dot_fu_364_C_array_0_d0),
    .C_array_0_q0(dense_13_output_arra_7_q0),
    .C_array_1_address0(grp_k2c_dot_fu_364_C_array_1_address0),
    .C_array_1_ce0(grp_k2c_dot_fu_364_C_array_1_ce0),
    .C_array_1_we0(grp_k2c_dot_fu_364_C_array_1_we0),
    .C_array_1_d0(grp_k2c_dot_fu_364_C_array_1_d0),
    .C_array_1_q0(dense_13_output_arra_6_q0),
    .C_array_2_address0(grp_k2c_dot_fu_364_C_array_2_address0),
    .C_array_2_ce0(grp_k2c_dot_fu_364_C_array_2_ce0),
    .C_array_2_we0(grp_k2c_dot_fu_364_C_array_2_we0),
    .C_array_2_d0(grp_k2c_dot_fu_364_C_array_2_d0),
    .C_array_2_q0(dense_13_output_arra_5_q0),
    .C_array_3_address0(grp_k2c_dot_fu_364_C_array_3_address0),
    .C_array_3_ce0(grp_k2c_dot_fu_364_C_array_3_ce0),
    .C_array_3_we0(grp_k2c_dot_fu_364_C_array_3_we0),
    .C_array_3_d0(grp_k2c_dot_fu_364_C_array_3_d0),
    .C_array_3_q0(dense_13_output_arra_4_q0),
    .C_array_4_address0(grp_k2c_dot_fu_364_C_array_4_address0),
    .C_array_4_ce0(grp_k2c_dot_fu_364_C_array_4_ce0),
    .C_array_4_we0(grp_k2c_dot_fu_364_C_array_4_we0),
    .C_array_4_d0(grp_k2c_dot_fu_364_C_array_4_d0),
    .C_array_4_q0(dense_13_output_arra_3_q0),
    .C_array_5_address0(grp_k2c_dot_fu_364_C_array_5_address0),
    .C_array_5_ce0(grp_k2c_dot_fu_364_C_array_5_ce0),
    .C_array_5_we0(grp_k2c_dot_fu_364_C_array_5_we0),
    .C_array_5_d0(grp_k2c_dot_fu_364_C_array_5_d0),
    .C_array_5_q0(dense_13_output_arra_2_q0),
    .C_array_6_address0(grp_k2c_dot_fu_364_C_array_6_address0),
    .C_array_6_ce0(grp_k2c_dot_fu_364_C_array_6_ce0),
    .C_array_6_we0(grp_k2c_dot_fu_364_C_array_6_we0),
    .C_array_6_d0(grp_k2c_dot_fu_364_C_array_6_d0),
    .C_array_6_q0(dense_13_output_arra_1_q0),
    .C_array_7_address0(grp_k2c_dot_fu_364_C_array_7_address0),
    .C_array_7_ce0(grp_k2c_dot_fu_364_C_array_7_ce0),
    .C_array_7_we0(grp_k2c_dot_fu_364_C_array_7_we0),
    .C_array_7_d0(grp_k2c_dot_fu_364_C_array_7_d0),
    .C_array_7_q0(dense_13_output_arra_q0),
    .A_array_0_address0(grp_k2c_dot_fu_364_A_array_0_address0),
    .A_array_0_ce0(grp_k2c_dot_fu_364_A_array_0_ce0),
    .A_array_0_q0(input_array_q0),
    .A_array_1_address0(grp_k2c_dot_fu_364_A_array_1_address0),
    .A_array_1_ce0(grp_k2c_dot_fu_364_A_array_1_ce0),
    .A_array_1_q0(input_array8_q0),
    .A_array_2_address0(grp_k2c_dot_fu_364_A_array_2_address0),
    .A_array_2_ce0(grp_k2c_dot_fu_364_A_array_2_ce0),
    .A_array_2_q0(input_array9_q0),
    .A_array_3_address0(grp_k2c_dot_fu_364_A_array_3_address0),
    .A_array_3_ce0(grp_k2c_dot_fu_364_A_array_3_ce0),
    .A_array_3_q0(input_array10_q0),
    .A_array_4_address0(grp_k2c_dot_fu_364_A_array_4_address0),
    .A_array_4_ce0(grp_k2c_dot_fu_364_A_array_4_ce0),
    .A_array_4_q0(input_array11_q0),
    .A_array_5_address0(grp_k2c_dot_fu_364_A_array_5_address0),
    .A_array_5_ce0(grp_k2c_dot_fu_364_A_array_5_ce0),
    .A_array_5_q0(input_array12_q0),
    .A_array_6_address0(grp_k2c_dot_fu_364_A_array_6_address0),
    .A_array_6_ce0(grp_k2c_dot_fu_364_A_array_6_ce0),
    .A_array_6_q0(input_array13_q0),
    .A_array_7_address0(grp_k2c_dot_fu_364_A_array_7_address0),
    .A_array_7_ce0(grp_k2c_dot_fu_364_A_array_7_ce0),
    .A_array_7_q0(input_array14_q0),
    .A_dim(input_dim),
    .A_numel_read(input_numel_read),
    .A_shape_address0(grp_k2c_dot_fu_364_A_shape_address0),
    .A_shape_ce0(grp_k2c_dot_fu_364_A_shape_ce0),
    .A_shape_q0(input_shape_q0),
    .B_dim(kernel_dim),
    .B_numel_read(dense_13_kernel_nume),
    .axesA_0_read(tmp_14_reg_796)
);

k2c_affine_matmul grp_k2c_affine_matmul_fu_430(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_k2c_affine_matmul_fu_430_ap_start),
    .ap_done(grp_k2c_affine_matmul_fu_430_ap_done),
    .ap_idle(grp_k2c_affine_matmul_fu_430_ap_idle),
    .ap_ready(grp_k2c_affine_matmul_fu_430_ap_ready),
    .C_0_address0(grp_k2c_affine_matmul_fu_430_C_0_address0),
    .C_0_ce0(grp_k2c_affine_matmul_fu_430_C_0_ce0),
    .C_0_we0(grp_k2c_affine_matmul_fu_430_C_0_we0),
    .C_0_d0(grp_k2c_affine_matmul_fu_430_C_0_d0),
    .C_1_address0(grp_k2c_affine_matmul_fu_430_C_1_address0),
    .C_1_ce0(grp_k2c_affine_matmul_fu_430_C_1_ce0),
    .C_1_we0(grp_k2c_affine_matmul_fu_430_C_1_we0),
    .C_1_d0(grp_k2c_affine_matmul_fu_430_C_1_d0),
    .C_2_address0(grp_k2c_affine_matmul_fu_430_C_2_address0),
    .C_2_ce0(grp_k2c_affine_matmul_fu_430_C_2_ce0),
    .C_2_we0(grp_k2c_affine_matmul_fu_430_C_2_we0),
    .C_2_d0(grp_k2c_affine_matmul_fu_430_C_2_d0),
    .C_3_address0(grp_k2c_affine_matmul_fu_430_C_3_address0),
    .C_3_ce0(grp_k2c_affine_matmul_fu_430_C_3_ce0),
    .C_3_we0(grp_k2c_affine_matmul_fu_430_C_3_we0),
    .C_3_d0(grp_k2c_affine_matmul_fu_430_C_3_d0),
    .C_4_address0(grp_k2c_affine_matmul_fu_430_C_4_address0),
    .C_4_ce0(grp_k2c_affine_matmul_fu_430_C_4_ce0),
    .C_4_we0(grp_k2c_affine_matmul_fu_430_C_4_we0),
    .C_4_d0(grp_k2c_affine_matmul_fu_430_C_4_d0),
    .C_5_address0(grp_k2c_affine_matmul_fu_430_C_5_address0),
    .C_5_ce0(grp_k2c_affine_matmul_fu_430_C_5_ce0),
    .C_5_we0(grp_k2c_affine_matmul_fu_430_C_5_we0),
    .C_5_d0(grp_k2c_affine_matmul_fu_430_C_5_d0),
    .C_6_address0(grp_k2c_affine_matmul_fu_430_C_6_address0),
    .C_6_ce0(grp_k2c_affine_matmul_fu_430_C_6_ce0),
    .C_6_we0(grp_k2c_affine_matmul_fu_430_C_6_we0),
    .C_6_d0(grp_k2c_affine_matmul_fu_430_C_6_d0),
    .C_7_address0(grp_k2c_affine_matmul_fu_430_C_7_address0),
    .C_7_ce0(grp_k2c_affine_matmul_fu_430_C_7_ce0),
    .C_7_we0(grp_k2c_affine_matmul_fu_430_C_7_we0),
    .C_7_d0(grp_k2c_affine_matmul_fu_430_C_7_d0),
    .A_0_address0(grp_k2c_affine_matmul_fu_430_A_0_address0),
    .A_0_ce0(grp_k2c_affine_matmul_fu_430_A_0_ce0),
    .A_0_q0(input_array_q0),
    .A_1_address0(grp_k2c_affine_matmul_fu_430_A_1_address0),
    .A_1_ce0(grp_k2c_affine_matmul_fu_430_A_1_ce0),
    .A_1_q0(input_array8_q0),
    .A_2_address0(grp_k2c_affine_matmul_fu_430_A_2_address0),
    .A_2_ce0(grp_k2c_affine_matmul_fu_430_A_2_ce0),
    .A_2_q0(input_array9_q0),
    .A_3_address0(grp_k2c_affine_matmul_fu_430_A_3_address0),
    .A_3_ce0(grp_k2c_affine_matmul_fu_430_A_3_ce0),
    .A_3_q0(input_array10_q0),
    .A_4_address0(grp_k2c_affine_matmul_fu_430_A_4_address0),
    .A_4_ce0(grp_k2c_affine_matmul_fu_430_A_4_ce0),
    .A_4_q0(input_array11_q0),
    .A_5_address0(grp_k2c_affine_matmul_fu_430_A_5_address0),
    .A_5_ce0(grp_k2c_affine_matmul_fu_430_A_5_ce0),
    .A_5_q0(input_array12_q0),
    .A_6_address0(grp_k2c_affine_matmul_fu_430_A_6_address0),
    .A_6_ce0(grp_k2c_affine_matmul_fu_430_A_6_ce0),
    .A_6_q0(input_array13_q0),
    .A_7_address0(grp_k2c_affine_matmul_fu_430_A_7_address0),
    .A_7_ce0(grp_k2c_affine_matmul_fu_430_A_7_ce0),
    .A_7_q0(input_array14_q0),
    .d_address0(grp_k2c_affine_matmul_fu_430_d_address0),
    .d_ce0(grp_k2c_affine_matmul_fu_430_d_ce0),
    .d_q0(dense_13_bias_array_q0),
    .outrows(outrows1_reg_893)
);

k2c_bias_add grp_k2c_bias_add_fu_485(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_k2c_bias_add_fu_485_ap_start),
    .ap_done(grp_k2c_bias_add_fu_485_ap_done),
    .ap_idle(grp_k2c_bias_add_fu_485_ap_idle),
    .ap_ready(grp_k2c_bias_add_fu_485_ap_ready),
    .A_array_0_address0(grp_k2c_bias_add_fu_485_A_array_0_address0),
    .A_array_0_ce0(grp_k2c_bias_add_fu_485_A_array_0_ce0),
    .A_array_0_we0(grp_k2c_bias_add_fu_485_A_array_0_we0),
    .A_array_0_d0(grp_k2c_bias_add_fu_485_A_array_0_d0),
    .A_array_0_q0(dense_13_output_arra_7_q0),
    .A_array_1_address0(grp_k2c_bias_add_fu_485_A_array_1_address0),
    .A_array_1_ce0(grp_k2c_bias_add_fu_485_A_array_1_ce0),
    .A_array_1_we0(grp_k2c_bias_add_fu_485_A_array_1_we0),
    .A_array_1_d0(grp_k2c_bias_add_fu_485_A_array_1_d0),
    .A_array_1_q0(dense_13_output_arra_6_q0),
    .A_array_2_address0(grp_k2c_bias_add_fu_485_A_array_2_address0),
    .A_array_2_ce0(grp_k2c_bias_add_fu_485_A_array_2_ce0),
    .A_array_2_we0(grp_k2c_bias_add_fu_485_A_array_2_we0),
    .A_array_2_d0(grp_k2c_bias_add_fu_485_A_array_2_d0),
    .A_array_2_q0(dense_13_output_arra_5_q0),
    .A_array_3_address0(grp_k2c_bias_add_fu_485_A_array_3_address0),
    .A_array_3_ce0(grp_k2c_bias_add_fu_485_A_array_3_ce0),
    .A_array_3_we0(grp_k2c_bias_add_fu_485_A_array_3_we0),
    .A_array_3_d0(grp_k2c_bias_add_fu_485_A_array_3_d0),
    .A_array_3_q0(dense_13_output_arra_4_q0),
    .A_array_4_address0(grp_k2c_bias_add_fu_485_A_array_4_address0),
    .A_array_4_ce0(grp_k2c_bias_add_fu_485_A_array_4_ce0),
    .A_array_4_we0(grp_k2c_bias_add_fu_485_A_array_4_we0),
    .A_array_4_d0(grp_k2c_bias_add_fu_485_A_array_4_d0),
    .A_array_4_q0(dense_13_output_arra_3_q0),
    .A_array_5_address0(grp_k2c_bias_add_fu_485_A_array_5_address0),
    .A_array_5_ce0(grp_k2c_bias_add_fu_485_A_array_5_ce0),
    .A_array_5_we0(grp_k2c_bias_add_fu_485_A_array_5_we0),
    .A_array_5_d0(grp_k2c_bias_add_fu_485_A_array_5_d0),
    .A_array_5_q0(dense_13_output_arra_2_q0),
    .A_array_6_address0(grp_k2c_bias_add_fu_485_A_array_6_address0),
    .A_array_6_ce0(grp_k2c_bias_add_fu_485_A_array_6_ce0),
    .A_array_6_we0(grp_k2c_bias_add_fu_485_A_array_6_we0),
    .A_array_6_d0(grp_k2c_bias_add_fu_485_A_array_6_d0),
    .A_array_6_q0(dense_13_output_arra_1_q0),
    .A_array_7_address0(grp_k2c_bias_add_fu_485_A_array_7_address0),
    .A_array_7_ce0(grp_k2c_bias_add_fu_485_A_array_7_ce0),
    .A_array_7_we0(grp_k2c_bias_add_fu_485_A_array_7_we0),
    .A_array_7_d0(grp_k2c_bias_add_fu_485_A_array_7_d0),
    .A_array_7_q0(dense_13_output_arra_q0),
    .A_numel_read(output_numel_read),
    .b_numel_read(dense_13_bias_numel)
);

sample_fcmp_32ns_Ffa #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
sample_fcmp_32ns_Ffa_U105(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_509_p0),
    .din1(32'd0),
    .ce(1'b1),
    .opcode(5'd5),
    .dout(grp_fu_509_p2)
);

sample_mux_864_32rcU #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
sample_mux_864_32rcU_U106(
    .din0(dense_13_output_arra_7_q0),
    .din1(dense_13_output_arra_6_q0),
    .din2(dense_13_output_arra_5_q0),
    .din3(dense_13_output_arra_4_q0),
    .din4(dense_13_output_arra_3_q0),
    .din5(dense_13_output_arra_2_q0),
    .din6(dense_13_output_arra_1_q0),
    .din7(dense_13_output_arra_q0),
    .din8(tmp_28_fu_593_p9),
    .dout(tmp_28_fu_593_p10)
);

sample_mux_864_32rcU #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
sample_mux_864_32rcU_U107(
    .din0(dense_13_output_arra_7_q0),
    .din1(dense_13_output_arra_6_q0),
    .din2(dense_13_output_arra_5_q0),
    .din3(dense_13_output_arra_4_q0),
    .din4(dense_13_output_arra_3_q0),
    .din5(dense_13_output_arra_2_q0),
    .din6(dense_13_output_arra_1_q0),
    .din7(dense_13_output_arra_q0),
    .din8(tmp_s_fu_706_p9),
    .dout(tmp_s_fu_706_p10)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_k2c_affine_matmul_fu_430_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_k2c_affine_matmul_fu_430_ap_start_reg <= 1'b1;
        end else if ((grp_k2c_affine_matmul_fu_430_ap_ready == 1'b1)) begin
            grp_k2c_affine_matmul_fu_430_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_k2c_bias_add_fu_485_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_k2c_bias_add_fu_485_ap_start_reg <= 1'b1;
        end else if ((grp_k2c_bias_add_fu_485_ap_ready == 1'b1)) begin
            grp_k2c_bias_add_fu_485_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_k2c_dot_fu_364_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (tmp_fu_514_p2 == 1'd0))) begin
            grp_k2c_dot_fu_364_ap_start_reg <= 1'b1;
        end else if ((grp_k2c_dot_fu_364_ap_ready == 1'b1)) begin
            grp_k2c_dot_fu_364_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_k2c_bias_add_fu_485_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        i_2_reg_342 <= 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        i_2_reg_342 <= i_28_reg_819;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_k2c_affine_matmul_fu_430_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        i_reg_353 <= 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        i_reg_353 <= i_29_reg_907;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (exitcond1_fu_666_p2 == 1'd0))) begin
        dense_13_output_arra_10_reg_927 <= newIndex2_cast_fu_691_p1;
        dense_13_output_arra_11_reg_932 <= newIndex2_cast_fu_691_p1;
        dense_13_output_arra_12_reg_937 <= newIndex2_cast_fu_691_p1;
        dense_13_output_arra_13_reg_942 <= newIndex2_cast_fu_691_p1;
        dense_13_output_arra_14_reg_947 <= newIndex2_cast_fu_691_p1;
        dense_13_output_arra_15_reg_952 <= newIndex2_cast_fu_691_p1;
        dense_13_output_arra_8_reg_917 <= newIndex2_cast_fu_691_p1;
        dense_13_output_arra_9_reg_922 <= newIndex2_cast_fu_691_p1;
        tmp_69_reg_912 <= tmp_69_fu_677_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (exitcond4_fu_553_p2 == 1'd0) & (tmp_reg_792 == 1'd0))) begin
        dense_13_output_arra_24_reg_829 <= newIndex_cast_fu_578_p1;
        dense_13_output_arra_25_reg_834 <= newIndex_cast_fu_578_p1;
        dense_13_output_arra_26_reg_839 <= newIndex_cast_fu_578_p1;
        dense_13_output_arra_27_reg_844 <= newIndex_cast_fu_578_p1;
        dense_13_output_arra_28_reg_849 <= newIndex_cast_fu_578_p1;
        dense_13_output_arra_29_reg_854 <= newIndex_cast_fu_578_p1;
        dense_13_output_arra_30_reg_859 <= newIndex_cast_fu_578_p1;
        dense_13_output_arra_31_reg_864 <= newIndex_cast_fu_578_p1;
        tmp_71_reg_824 <= tmp_71_fu_564_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (tmp_reg_792 == 1'd0))) begin
        i_28_reg_819 <= i_28_fu_558_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        i_29_reg_907 <= i_29_fu_671_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (tmp_fu_514_p2 == 1'd1))) begin
        icmp_reg_806 <= icmp_fu_542_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        notlhs4_reg_963 <= notlhs4_fu_745_p2;
        notrhs5_reg_968 <= notrhs5_fu_751_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        notlhs_reg_875 <= notlhs_fu_632_p2;
        notrhs_reg_880 <= notrhs_fu_638_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        outrows1_reg_893 <= outrows1_fu_653_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (tmp_fu_514_p2 == 1'd0))) begin
        tmp_14_reg_796 <= tmp_14_fu_520_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        tmp_26_reg_973 <= grp_fu_509_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_28_reg_869 <= tmp_28_fu_593_p10;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        tmp_31_reg_885 <= grp_fu_509_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_k2c_affine_matmul_fu_430_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        tmp_68_reg_899[63 : 7] <= tmp_68_fu_661_p2[63 : 7];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_reg_792 <= tmp_fu_514_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        tmp_s_reg_957 <= tmp_s_fu_706_p10;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state5) & ((exitcond4_fu_553_p2 == 1'd1) | (tmp_reg_792 == 1'd1))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & ((exitcond4_fu_553_p2 == 1'd1) | (tmp_reg_792 == 1'd1)))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_bias_array_address0 = 7'd0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_bias_array_address0 = grp_k2c_affine_matmul_fu_430_d_address0;
    end else begin
        dense_13_bias_array_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_bias_array_ce0 = 1'b0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_bias_array_ce0 = grp_k2c_affine_matmul_fu_430_d_ce0;
    end else begin
        dense_13_bias_array_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        dense_13_output_arra_1_address0 = dense_13_output_arra_14_reg_947;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        dense_13_output_arra_1_address0 = newIndex2_cast_fu_691_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        dense_13_output_arra_1_address0 = dense_13_output_arra_30_reg_859;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        dense_13_output_arra_1_address0 = newIndex_cast_fu_578_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_1_address0 = grp_k2c_bias_add_fu_485_A_array_6_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_1_address0 = grp_k2c_affine_matmul_fu_430_C_6_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_1_address0 = grp_k2c_dot_fu_364_C_array_6_address0;
    end else begin
        dense_13_output_arra_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state5))) begin
        dense_13_output_arra_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_1_ce0 = grp_k2c_bias_add_fu_485_A_array_6_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_1_ce0 = grp_k2c_affine_matmul_fu_430_C_6_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_1_ce0 = grp_k2c_dot_fu_364_C_array_6_ce0;
    end else begin
        dense_13_output_arra_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state16))) begin
        dense_13_output_arra_1_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_1_d0 = grp_k2c_bias_add_fu_485_A_array_6_d0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_1_d0 = grp_k2c_affine_matmul_fu_430_C_6_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_1_d0 = grp_k2c_dot_fu_364_C_array_6_d0;
    end else begin
        dense_13_output_arra_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_71_reg_824 == 3'd6) & (1'b1 == ap_CS_fsm_state9) & (tmp_32_fu_648_p2 == 1'd1)) | ((tmp_69_reg_912 == 3'd6) & (1'b1 == ap_CS_fsm_state16) & (tmp_27_fu_761_p2 == 1'd1)))) begin
        dense_13_output_arra_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_1_we0 = grp_k2c_bias_add_fu_485_A_array_6_we0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_1_we0 = grp_k2c_affine_matmul_fu_430_C_6_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_1_we0 = grp_k2c_dot_fu_364_C_array_6_we0;
    end else begin
        dense_13_output_arra_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        dense_13_output_arra_2_address0 = dense_13_output_arra_13_reg_942;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        dense_13_output_arra_2_address0 = newIndex2_cast_fu_691_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        dense_13_output_arra_2_address0 = dense_13_output_arra_29_reg_854;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        dense_13_output_arra_2_address0 = newIndex_cast_fu_578_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_2_address0 = grp_k2c_bias_add_fu_485_A_array_5_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_2_address0 = grp_k2c_affine_matmul_fu_430_C_5_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_2_address0 = grp_k2c_dot_fu_364_C_array_5_address0;
    end else begin
        dense_13_output_arra_2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state5))) begin
        dense_13_output_arra_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_2_ce0 = grp_k2c_bias_add_fu_485_A_array_5_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_2_ce0 = grp_k2c_affine_matmul_fu_430_C_5_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_2_ce0 = grp_k2c_dot_fu_364_C_array_5_ce0;
    end else begin
        dense_13_output_arra_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state16))) begin
        dense_13_output_arra_2_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_2_d0 = grp_k2c_bias_add_fu_485_A_array_5_d0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_2_d0 = grp_k2c_affine_matmul_fu_430_C_5_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_2_d0 = grp_k2c_dot_fu_364_C_array_5_d0;
    end else begin
        dense_13_output_arra_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_71_reg_824 == 3'd5) & (1'b1 == ap_CS_fsm_state9) & (tmp_32_fu_648_p2 == 1'd1)) | ((tmp_69_reg_912 == 3'd5) & (1'b1 == ap_CS_fsm_state16) & (tmp_27_fu_761_p2 == 1'd1)))) begin
        dense_13_output_arra_2_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_2_we0 = grp_k2c_bias_add_fu_485_A_array_5_we0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_2_we0 = grp_k2c_affine_matmul_fu_430_C_5_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_2_we0 = grp_k2c_dot_fu_364_C_array_5_we0;
    end else begin
        dense_13_output_arra_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        dense_13_output_arra_3_address0 = dense_13_output_arra_12_reg_937;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        dense_13_output_arra_3_address0 = newIndex2_cast_fu_691_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        dense_13_output_arra_3_address0 = dense_13_output_arra_28_reg_849;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        dense_13_output_arra_3_address0 = newIndex_cast_fu_578_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_3_address0 = grp_k2c_bias_add_fu_485_A_array_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_3_address0 = grp_k2c_affine_matmul_fu_430_C_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_3_address0 = grp_k2c_dot_fu_364_C_array_4_address0;
    end else begin
        dense_13_output_arra_3_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state5))) begin
        dense_13_output_arra_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_3_ce0 = grp_k2c_bias_add_fu_485_A_array_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_3_ce0 = grp_k2c_affine_matmul_fu_430_C_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_3_ce0 = grp_k2c_dot_fu_364_C_array_4_ce0;
    end else begin
        dense_13_output_arra_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state16))) begin
        dense_13_output_arra_3_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_3_d0 = grp_k2c_bias_add_fu_485_A_array_4_d0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_3_d0 = grp_k2c_affine_matmul_fu_430_C_4_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_3_d0 = grp_k2c_dot_fu_364_C_array_4_d0;
    end else begin
        dense_13_output_arra_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_71_reg_824 == 3'd4) & (1'b1 == ap_CS_fsm_state9) & (tmp_32_fu_648_p2 == 1'd1)) | ((tmp_69_reg_912 == 3'd4) & (1'b1 == ap_CS_fsm_state16) & (tmp_27_fu_761_p2 == 1'd1)))) begin
        dense_13_output_arra_3_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_3_we0 = grp_k2c_bias_add_fu_485_A_array_4_we0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_3_we0 = grp_k2c_affine_matmul_fu_430_C_4_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_3_we0 = grp_k2c_dot_fu_364_C_array_4_we0;
    end else begin
        dense_13_output_arra_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        dense_13_output_arra_4_address0 = dense_13_output_arra_11_reg_932;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        dense_13_output_arra_4_address0 = newIndex2_cast_fu_691_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        dense_13_output_arra_4_address0 = dense_13_output_arra_27_reg_844;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        dense_13_output_arra_4_address0 = newIndex_cast_fu_578_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_4_address0 = grp_k2c_bias_add_fu_485_A_array_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_4_address0 = grp_k2c_affine_matmul_fu_430_C_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_4_address0 = grp_k2c_dot_fu_364_C_array_3_address0;
    end else begin
        dense_13_output_arra_4_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state5))) begin
        dense_13_output_arra_4_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_4_ce0 = grp_k2c_bias_add_fu_485_A_array_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_4_ce0 = grp_k2c_affine_matmul_fu_430_C_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_4_ce0 = grp_k2c_dot_fu_364_C_array_3_ce0;
    end else begin
        dense_13_output_arra_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state16))) begin
        dense_13_output_arra_4_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_4_d0 = grp_k2c_bias_add_fu_485_A_array_3_d0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_4_d0 = grp_k2c_affine_matmul_fu_430_C_3_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_4_d0 = grp_k2c_dot_fu_364_C_array_3_d0;
    end else begin
        dense_13_output_arra_4_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_71_reg_824 == 3'd3) & (1'b1 == ap_CS_fsm_state9) & (tmp_32_fu_648_p2 == 1'd1)) | ((tmp_69_reg_912 == 3'd3) & (1'b1 == ap_CS_fsm_state16) & (tmp_27_fu_761_p2 == 1'd1)))) begin
        dense_13_output_arra_4_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_4_we0 = grp_k2c_bias_add_fu_485_A_array_3_we0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_4_we0 = grp_k2c_affine_matmul_fu_430_C_3_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_4_we0 = grp_k2c_dot_fu_364_C_array_3_we0;
    end else begin
        dense_13_output_arra_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        dense_13_output_arra_5_address0 = dense_13_output_arra_10_reg_927;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        dense_13_output_arra_5_address0 = newIndex2_cast_fu_691_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        dense_13_output_arra_5_address0 = dense_13_output_arra_26_reg_839;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        dense_13_output_arra_5_address0 = newIndex_cast_fu_578_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_5_address0 = grp_k2c_bias_add_fu_485_A_array_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_5_address0 = grp_k2c_affine_matmul_fu_430_C_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_5_address0 = grp_k2c_dot_fu_364_C_array_2_address0;
    end else begin
        dense_13_output_arra_5_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state5))) begin
        dense_13_output_arra_5_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_5_ce0 = grp_k2c_bias_add_fu_485_A_array_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_5_ce0 = grp_k2c_affine_matmul_fu_430_C_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_5_ce0 = grp_k2c_dot_fu_364_C_array_2_ce0;
    end else begin
        dense_13_output_arra_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state16))) begin
        dense_13_output_arra_5_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_5_d0 = grp_k2c_bias_add_fu_485_A_array_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_5_d0 = grp_k2c_affine_matmul_fu_430_C_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_5_d0 = grp_k2c_dot_fu_364_C_array_2_d0;
    end else begin
        dense_13_output_arra_5_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_71_reg_824 == 3'd2) & (1'b1 == ap_CS_fsm_state9) & (tmp_32_fu_648_p2 == 1'd1)) | ((tmp_69_reg_912 == 3'd2) & (1'b1 == ap_CS_fsm_state16) & (tmp_27_fu_761_p2 == 1'd1)))) begin
        dense_13_output_arra_5_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_5_we0 = grp_k2c_bias_add_fu_485_A_array_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_5_we0 = grp_k2c_affine_matmul_fu_430_C_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_5_we0 = grp_k2c_dot_fu_364_C_array_2_we0;
    end else begin
        dense_13_output_arra_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        dense_13_output_arra_6_address0 = dense_13_output_arra_9_reg_922;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        dense_13_output_arra_6_address0 = newIndex2_cast_fu_691_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        dense_13_output_arra_6_address0 = dense_13_output_arra_25_reg_834;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        dense_13_output_arra_6_address0 = newIndex_cast_fu_578_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_6_address0 = grp_k2c_bias_add_fu_485_A_array_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_6_address0 = grp_k2c_affine_matmul_fu_430_C_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_6_address0 = grp_k2c_dot_fu_364_C_array_1_address0;
    end else begin
        dense_13_output_arra_6_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state5))) begin
        dense_13_output_arra_6_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_6_ce0 = grp_k2c_bias_add_fu_485_A_array_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_6_ce0 = grp_k2c_affine_matmul_fu_430_C_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_6_ce0 = grp_k2c_dot_fu_364_C_array_1_ce0;
    end else begin
        dense_13_output_arra_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state16))) begin
        dense_13_output_arra_6_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_6_d0 = grp_k2c_bias_add_fu_485_A_array_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_6_d0 = grp_k2c_affine_matmul_fu_430_C_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_6_d0 = grp_k2c_dot_fu_364_C_array_1_d0;
    end else begin
        dense_13_output_arra_6_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_71_reg_824 == 3'd1) & (1'b1 == ap_CS_fsm_state9) & (tmp_32_fu_648_p2 == 1'd1)) | ((tmp_69_reg_912 == 3'd1) & (1'b1 == ap_CS_fsm_state16) & (tmp_27_fu_761_p2 == 1'd1)))) begin
        dense_13_output_arra_6_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_6_we0 = grp_k2c_bias_add_fu_485_A_array_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_6_we0 = grp_k2c_affine_matmul_fu_430_C_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_6_we0 = grp_k2c_dot_fu_364_C_array_1_we0;
    end else begin
        dense_13_output_arra_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        dense_13_output_arra_7_address0 = dense_13_output_arra_8_reg_917;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        dense_13_output_arra_7_address0 = newIndex2_cast_fu_691_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        dense_13_output_arra_7_address0 = dense_13_output_arra_24_reg_829;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        dense_13_output_arra_7_address0 = newIndex_cast_fu_578_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_7_address0 = grp_k2c_bias_add_fu_485_A_array_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_7_address0 = grp_k2c_affine_matmul_fu_430_C_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_7_address0 = grp_k2c_dot_fu_364_C_array_0_address0;
    end else begin
        dense_13_output_arra_7_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state5))) begin
        dense_13_output_arra_7_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_7_ce0 = grp_k2c_bias_add_fu_485_A_array_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_7_ce0 = grp_k2c_affine_matmul_fu_430_C_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_7_ce0 = grp_k2c_dot_fu_364_C_array_0_ce0;
    end else begin
        dense_13_output_arra_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state16))) begin
        dense_13_output_arra_7_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_7_d0 = grp_k2c_bias_add_fu_485_A_array_0_d0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_7_d0 = grp_k2c_affine_matmul_fu_430_C_0_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_7_d0 = grp_k2c_dot_fu_364_C_array_0_d0;
    end else begin
        dense_13_output_arra_7_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_71_reg_824 == 3'd0) & (1'b1 == ap_CS_fsm_state9) & (tmp_32_fu_648_p2 == 1'd1)) | ((tmp_69_reg_912 == 3'd0) & (1'b1 == ap_CS_fsm_state16) & (tmp_27_fu_761_p2 == 1'd1)))) begin
        dense_13_output_arra_7_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_7_we0 = grp_k2c_bias_add_fu_485_A_array_0_we0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_7_we0 = grp_k2c_affine_matmul_fu_430_C_0_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_7_we0 = grp_k2c_dot_fu_364_C_array_0_we0;
    end else begin
        dense_13_output_arra_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        dense_13_output_arra_address0 = dense_13_output_arra_15_reg_952;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        dense_13_output_arra_address0 = newIndex2_cast_fu_691_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        dense_13_output_arra_address0 = dense_13_output_arra_31_reg_864;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        dense_13_output_arra_address0 = newIndex_cast_fu_578_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_address0 = grp_k2c_bias_add_fu_485_A_array_7_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_address0 = grp_k2c_affine_matmul_fu_430_C_7_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_address0 = grp_k2c_dot_fu_364_C_array_7_address0;
    end else begin
        dense_13_output_arra_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state5))) begin
        dense_13_output_arra_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_ce0 = grp_k2c_bias_add_fu_485_A_array_7_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_ce0 = grp_k2c_affine_matmul_fu_430_C_7_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_ce0 = grp_k2c_dot_fu_364_C_array_7_ce0;
    end else begin
        dense_13_output_arra_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state16))) begin
        dense_13_output_arra_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_d0 = grp_k2c_bias_add_fu_485_A_array_7_d0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_d0 = grp_k2c_affine_matmul_fu_430_C_7_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_d0 = grp_k2c_dot_fu_364_C_array_7_d0;
    end else begin
        dense_13_output_arra_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_71_reg_824 == 3'd7) & (1'b1 == ap_CS_fsm_state9) & (tmp_32_fu_648_p2 == 1'd1)) | ((tmp_69_reg_912 == 3'd7) & (1'b1 == ap_CS_fsm_state16) & (tmp_27_fu_761_p2 == 1'd1)))) begin
        dense_13_output_arra_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_13_output_arra_we0 = grp_k2c_bias_add_fu_485_A_array_7_we0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_13_output_arra_we0 = grp_k2c_affine_matmul_fu_430_C_7_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_13_output_arra_we0 = grp_k2c_dot_fu_364_C_array_7_we0;
    end else begin
        dense_13_output_arra_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_509_p0 = tmp_s_reg_957;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_509_p0 = tmp_28_reg_869;
    end else begin
        grp_fu_509_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        input_array10_address0 = grp_k2c_affine_matmul_fu_430_A_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_array10_address0 = grp_k2c_dot_fu_364_A_array_3_address0;
    end else begin
        input_array10_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        input_array10_ce0 = grp_k2c_affine_matmul_fu_430_A_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_array10_ce0 = grp_k2c_dot_fu_364_A_array_3_ce0;
    end else begin
        input_array10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        input_array11_address0 = grp_k2c_affine_matmul_fu_430_A_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_array11_address0 = grp_k2c_dot_fu_364_A_array_4_address0;
    end else begin
        input_array11_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        input_array11_ce0 = grp_k2c_affine_matmul_fu_430_A_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_array11_ce0 = grp_k2c_dot_fu_364_A_array_4_ce0;
    end else begin
        input_array11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        input_array12_address0 = grp_k2c_affine_matmul_fu_430_A_5_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_array12_address0 = grp_k2c_dot_fu_364_A_array_5_address0;
    end else begin
        input_array12_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        input_array12_ce0 = grp_k2c_affine_matmul_fu_430_A_5_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_array12_ce0 = grp_k2c_dot_fu_364_A_array_5_ce0;
    end else begin
        input_array12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        input_array13_address0 = grp_k2c_affine_matmul_fu_430_A_6_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_array13_address0 = grp_k2c_dot_fu_364_A_array_6_address0;
    end else begin
        input_array13_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        input_array13_ce0 = grp_k2c_affine_matmul_fu_430_A_6_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_array13_ce0 = grp_k2c_dot_fu_364_A_array_6_ce0;
    end else begin
        input_array13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        input_array14_address0 = grp_k2c_affine_matmul_fu_430_A_7_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_array14_address0 = grp_k2c_dot_fu_364_A_array_7_address0;
    end else begin
        input_array14_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        input_array14_ce0 = grp_k2c_affine_matmul_fu_430_A_7_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_array14_ce0 = grp_k2c_dot_fu_364_A_array_7_ce0;
    end else begin
        input_array14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        input_array8_address0 = grp_k2c_affine_matmul_fu_430_A_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_array8_address0 = grp_k2c_dot_fu_364_A_array_1_address0;
    end else begin
        input_array8_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        input_array8_ce0 = grp_k2c_affine_matmul_fu_430_A_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_array8_ce0 = grp_k2c_dot_fu_364_A_array_1_ce0;
    end else begin
        input_array8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        input_array9_address0 = grp_k2c_affine_matmul_fu_430_A_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_array9_address0 = grp_k2c_dot_fu_364_A_array_2_address0;
    end else begin
        input_array9_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        input_array9_ce0 = grp_k2c_affine_matmul_fu_430_A_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_array9_ce0 = grp_k2c_dot_fu_364_A_array_2_ce0;
    end else begin
        input_array9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        input_array_address0 = grp_k2c_affine_matmul_fu_430_A_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_array_address0 = grp_k2c_dot_fu_364_A_array_0_address0;
    end else begin
        input_array_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        input_array_ce0 = grp_k2c_affine_matmul_fu_430_A_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_array_ce0 = grp_k2c_dot_fu_364_A_array_0_ce0;
    end else begin
        input_array_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (tmp_fu_514_p2 == 1'd1))) begin
        input_shape_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_shape_address0 = grp_k2c_dot_fu_364_A_shape_address0;
    end else begin
        input_shape_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (tmp_fu_514_p2 == 1'd1))) begin
        input_shape_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_shape_ce0 = grp_k2c_dot_fu_364_A_shape_ce0;
    end else begin
        input_shape_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (tmp_fu_514_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (tmp_fu_514_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_k2c_dot_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_k2c_bias_add_fu_485_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & ((exitcond4_fu_553_p2 == 1'd1) | (tmp_reg_792 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_k2c_affine_matmul_fu_430_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (exitcond1_fu_666_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign exitcond1_fu_666_p2 = ((i_reg_353 == tmp_68_reg_899) ? 1'b1 : 1'b0);

assign exitcond4_fu_553_p2 = ((i_2_reg_342 == output_numel_read) ? 1'b1 : 1'b0);

assign grp_k2c_affine_matmul_fu_430_ap_start = grp_k2c_affine_matmul_fu_430_ap_start_reg;

assign grp_k2c_bias_add_fu_485_ap_start = grp_k2c_bias_add_fu_485_ap_start_reg;

assign grp_k2c_dot_fu_364_ap_start = grp_k2c_dot_fu_364_ap_start_reg;

assign i_28_fu_558_p2 = (i_2_reg_342 + 64'd1);

assign i_29_fu_671_p2 = (i_reg_353 + 64'd1);

assign icmp_fu_542_p2 = ((tmp_67_fu_532_p4 != 63'd0) ? 1'b1 : 1'b0);

assign newIndex2_cast_fu_691_p1 = newIndex2_fu_681_p4;

assign newIndex2_fu_681_p4 = {{i_reg_353[8:3]}};

assign newIndex_cast_fu_578_p1 = newIndex_fu_568_p4;

assign newIndex_fu_568_p4 = {{i_2_reg_342[8:3]}};

assign notlhs4_fu_745_p2 = ((tmp_24_fu_731_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notlhs_fu_632_p2 = ((tmp_29_fu_618_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notrhs5_fu_751_p2 = ((tmp_70_fu_741_p1 == 23'd0) ? 1'b1 : 1'b0);

assign notrhs_fu_638_p2 = ((tmp_72_fu_628_p1 == 23'd0) ? 1'b1 : 1'b0);

assign outrows1_fu_653_p3 = ((icmp_reg_806[0:0] === 1'b1) ? input_shape_q0 : 64'd1);

assign p_to_int2_fu_615_p1 = tmp_28_reg_869;

assign p_to_int_fu_728_p1 = tmp_s_reg_957;

assign tmp_14_fu_520_p2 = ($signed(input_dim) + $signed(64'd18446744073709551615));

assign tmp_24_fu_731_p4 = {{p_to_int_fu_728_p1[30:23]}};

assign tmp_25_fu_757_p2 = (notrhs5_reg_968 | notlhs4_reg_963);

assign tmp_27_fu_761_p2 = (tmp_26_reg_973 & tmp_25_fu_757_p2);

assign tmp_28_fu_593_p9 = tmp_71_reg_824;

assign tmp_29_fu_618_p4 = {{p_to_int2_fu_615_p1[30:23]}};

assign tmp_30_fu_644_p2 = (notrhs_reg_880 | notlhs_reg_875);

assign tmp_32_fu_648_p2 = (tmp_31_reg_885 & tmp_30_fu_644_p2);

assign tmp_67_fu_532_p4 = {{input_dim[63:1]}};

assign tmp_68_fu_661_p2 = outrows1_reg_893 << 64'd7;

assign tmp_69_fu_677_p1 = i_reg_353[2:0];

assign tmp_70_fu_741_p1 = p_to_int_fu_728_p1[22:0];

assign tmp_71_fu_564_p1 = i_2_reg_342[2:0];

assign tmp_72_fu_628_p1 = p_to_int2_fu_615_p1[22:0];

assign tmp_fu_514_p2 = ((input_dim < 64'd3) ? 1'b1 : 1'b0);

assign tmp_s_fu_706_p9 = tmp_69_reg_912;

always @ (posedge ap_clk) begin
    tmp_68_reg_899[6:0] <= 7'b0000000;
end

endmodule //k2c_dense_3
