// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __k2c_bias_add_2_debnm_H__
#define __k2c_bias_add_2_debnm_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct k2c_bias_add_2_debnm_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 32;
  static const unsigned AddressRange = 16;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(k2c_bias_add_2_debnm_ram) {
        ram[0] = "0b10111100011010011001000000011110";
        ram[1] = "0b00111011010000010101100011100111";
        ram[2] = "0b00111101000010100100111001101010";
        ram[3] = "0b00111101001001000001011110101100";
        ram[4] = "0b00111101010110000100000100010101";
        ram[5] = "0b00111100110001101001101111111111";
        ram[6] = "0b00111011101001011001010001011010";
        ram[7] = "0b00111101001010100100001100000001";
        ram[8] = "0b00111100110101100001010101110110";
        ram[9] = "0b10111100010110101101100010110110";
        ram[10] = "0b00111100100100101110110011011011";
        ram[11] = "0b10111100000111100010001010010010";
        ram[12] = "0b00111101000110100011100001100110";
        ram[13] = "0b10111100001001100101010001000010";
        ram[14] = "0b00111100100111011010101010100000";
        ram[15] = "0b10111100101001011101110010100001";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(k2c_bias_add_2_debnm) {


static const unsigned DataWidth = 32;
static const unsigned AddressRange = 16;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


k2c_bias_add_2_debnm_ram* meminst;


SC_CTOR(k2c_bias_add_2_debnm) {
meminst = new k2c_bias_add_2_debnm_ram("k2c_bias_add_2_debnm_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~k2c_bias_add_2_debnm() {
    delete meminst;
}


};//endmodule
#endif
