// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module k2c_dense_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        output_numel_read,
        input_dim,
        input_numel_read,
        kernel_dim,
        dense_15_output_arra_address0,
        dense_15_output_arra_ce0,
        dense_15_output_arra_we0,
        dense_15_output_arra_d0,
        dense_15_output_arra_q0,
        dense_14_output_arra_address0,
        dense_14_output_arra_ce0,
        dense_14_output_arra_q0
);

parameter    ap_ST_fsm_state1 = 26'd1;
parameter    ap_ST_fsm_state2 = 26'd2;
parameter    ap_ST_fsm_state3 = 26'd4;
parameter    ap_ST_fsm_state4 = 26'd8;
parameter    ap_ST_fsm_state5 = 26'd16;
parameter    ap_ST_fsm_state6 = 26'd32;
parameter    ap_ST_fsm_state7 = 26'd64;
parameter    ap_ST_fsm_state8 = 26'd128;
parameter    ap_ST_fsm_state9 = 26'd256;
parameter    ap_ST_fsm_state10 = 26'd512;
parameter    ap_ST_fsm_state11 = 26'd1024;
parameter    ap_ST_fsm_state12 = 26'd2048;
parameter    ap_ST_fsm_state13 = 26'd4096;
parameter    ap_ST_fsm_state14 = 26'd8192;
parameter    ap_ST_fsm_state15 = 26'd16384;
parameter    ap_ST_fsm_state16 = 26'd32768;
parameter    ap_ST_fsm_state17 = 26'd65536;
parameter    ap_ST_fsm_state18 = 26'd131072;
parameter    ap_ST_fsm_state19 = 26'd262144;
parameter    ap_ST_fsm_state20 = 26'd524288;
parameter    ap_ST_fsm_state21 = 26'd1048576;
parameter    ap_ST_fsm_state22 = 26'd2097152;
parameter    ap_ST_fsm_state23 = 26'd4194304;
parameter    ap_ST_fsm_state24 = 26'd8388608;
parameter    ap_ST_fsm_state25 = 26'd16777216;
parameter    ap_ST_fsm_state26 = 26'd33554432;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] output_numel_read;
input  [63:0] input_dim;
input  [63:0] input_numel_read;
input  [63:0] kernel_dim;
output  [3:0] dense_15_output_arra_address0;
output   dense_15_output_arra_ce0;
output   dense_15_output_arra_we0;
output  [31:0] dense_15_output_arra_d0;
input  [31:0] dense_15_output_arra_q0;
output  [4:0] dense_14_output_arra_address0;
output   dense_14_output_arra_ce0;
input  [31:0] dense_14_output_arra_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] dense_15_output_arra_address0;
reg dense_15_output_arra_ce0;
reg dense_15_output_arra_we0;
reg[31:0] dense_15_output_arra_d0;
reg[4:0] dense_14_output_arra_address0;
reg dense_14_output_arra_ce0;

(* fsm_encoding = "none" *) reg   [25:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [8:0] dense_15_kernel_arra_address0;
reg    dense_15_kernel_arra_ce0;
wire   [31:0] dense_15_kernel_arra_q0;
reg   [3:0] dense_15_bias_array_address0;
reg    dense_15_bias_array_ce0;
wire   [31:0] dense_15_bias_array_q0;
reg   [63:0] dense_15_kernel_nume;
reg   [63:0] dense_15_bias_numel;
reg   [31:0] reg_238;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state23;
wire   [0:0] tmp_fu_244_p2;
reg   [0:0] tmp_reg_468;
wire   [63:0] tmp_16_fu_250_p2;
reg   [63:0] tmp_16_reg_472;
wire   [0:0] icmp_fu_272_p2;
reg   [0:0] icmp_reg_482;
wire   [5:0] p_s_fu_278_p3;
reg   [5:0] p_s_reg_487;
wire    ap_CS_fsm_state2;
wire    grp_k2c_dot_2_fu_192_ap_idle;
wire    grp_k2c_dot_2_fu_192_ap_ready;
wire    grp_k2c_dot_2_fu_192_ap_done;
wire   [63:0] j_fu_305_p2;
reg   [63:0] j_reg_504;
wire    ap_CS_fsm_state4;
wire   [0:0] exitcond_i_fu_300_p2;
reg   [3:0] dense_15_output_arra_4_reg_514;
wire   [63:0] i_31_fu_326_p2;
reg   [31:0] dense_15_bias_array_1_reg_524;
wire   [31:0] grp_fu_229_p2;
reg   [31:0] tmp_i_15_reg_529;
wire    ap_CS_fsm_state14;
wire   [63:0] i_34_fu_336_p2;
reg   [63:0] i_34_reg_537;
wire    ap_CS_fsm_state16;
reg   [3:0] dense_15_output_arra_6_reg_542;
wire   [0:0] exitcond4_fu_331_p2;
wire   [0:0] notlhs_fu_360_p2;
reg   [0:0] notlhs_reg_547;
wire    ap_CS_fsm_state18;
wire   [0:0] notrhs_fu_366_p2;
reg   [0:0] notrhs_reg_552;
wire   [0:0] grp_fu_233_p2;
reg   [0:0] tmp_23_reg_557;
wire    ap_CS_fsm_state19;
wire   [10:0] tmp_19_cast_cast_fu_381_p3;
reg   [10:0] tmp_19_cast_cast_reg_565;
wire    ap_CS_fsm_state21;
wire    grp_k2c_affine_matmul_2_fu_216_ap_idle;
wire    grp_k2c_affine_matmul_2_fu_216_ap_ready;
wire    grp_k2c_affine_matmul_2_fu_216_ap_done;
wire   [9:0] i_33_fu_402_p2;
reg   [9:0] i_33_reg_573;
wire    ap_CS_fsm_state22;
reg   [3:0] dense_15_output_arra_1_reg_578;
wire   [0:0] exitcond1_fu_397_p2;
wire   [0:0] notlhs3_fu_426_p2;
reg   [0:0] notlhs3_reg_583;
wire    ap_CS_fsm_state24;
wire   [0:0] notrhs4_fu_432_p2;
reg   [0:0] notrhs4_reg_588;
reg   [0:0] tmp_19_reg_593;
wire    ap_CS_fsm_state25;
wire    grp_k2c_dot_2_fu_192_ap_start;
wire   [3:0] grp_k2c_dot_2_fu_192_C_array_address0;
wire    grp_k2c_dot_2_fu_192_C_array_ce0;
wire    grp_k2c_dot_2_fu_192_C_array_we0;
wire   [31:0] grp_k2c_dot_2_fu_192_C_array_d0;
wire   [4:0] grp_k2c_dot_2_fu_192_A_array_address0;
wire    grp_k2c_dot_2_fu_192_A_array_ce0;
wire    grp_k2c_affine_matmul_2_fu_216_ap_start;
wire   [3:0] grp_k2c_affine_matmul_2_fu_216_C_address0;
wire    grp_k2c_affine_matmul_2_fu_216_C_ce0;
wire    grp_k2c_affine_matmul_2_fu_216_C_we0;
wire   [31:0] grp_k2c_affine_matmul_2_fu_216_C_d0;
wire   [4:0] grp_k2c_affine_matmul_2_fu_216_A_address0;
wire    grp_k2c_affine_matmul_2_fu_216_A_ce0;
wire   [8:0] grp_k2c_affine_matmul_2_fu_216_B_address0;
wire    grp_k2c_affine_matmul_2_fu_216_B_ce0;
wire   [3:0] grp_k2c_affine_matmul_2_fu_216_d_address0;
wire    grp_k2c_affine_matmul_2_fu_216_d_ce0;
reg   [63:0] i_i_reg_145;
reg   [63:0] j_i_reg_157;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state3;
wire   [0:0] tmp_i_fu_291_p2;
reg   [63:0] i_2_reg_169;
wire    ap_CS_fsm_state20;
reg   [9:0] i_reg_181;
wire    ap_CS_fsm_state26;
reg    grp_k2c_dot_2_fu_192_ap_start_reg;
reg    grp_k2c_affine_matmul_2_fu_216_ap_start_reg;
wire   [63:0] sum_i_cast_fu_321_p1;
wire   [63:0] i_cast1_fu_388_p1;
wire   [0:0] tmp_24_fu_376_p2;
wire   [0:0] tmp_20_fu_442_p2;
wire    ap_CS_fsm_state6;
wire   [62:0] tmp_61_fu_262_p4;
wire   [5:0] tmp_64_fu_311_p1;
wire   [5:0] tmp_63_fu_296_p1;
wire   [5:0] sum_i_fu_315_p2;
wire   [31:0] dense_15_output_arra_8_fu_342_p1;
wire   [7:0] tmp_21_fu_346_p4;
wire   [22:0] tmp_65_fu_356_p1;
wire   [0:0] tmp_22_fu_372_p2;
wire   [10:0] i_cast_fu_393_p1;
wire   [31:0] dense_15_output_arra_3_fu_408_p1;
wire   [7:0] tmp_s_fu_412_p4;
wire   [22:0] tmp_62_fu_422_p1;
wire   [0:0] tmp_18_fu_438_p2;
reg   [25:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 26'd1;
#0 dense_15_kernel_nume = 64'd512;
#0 dense_15_bias_numel = 64'd16;
#0 grp_k2c_dot_2_fu_192_ap_start_reg = 1'b0;
#0 grp_k2c_affine_matmul_2_fu_216_ap_start_reg = 1'b0;
end

k2c_dense_1_denseHfu #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
dense_15_kernel_arra_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_15_kernel_arra_address0),
    .ce0(dense_15_kernel_arra_ce0),
    .q0(dense_15_kernel_arra_q0)
);

k2c_dense_1_denseIfE #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
dense_15_bias_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_15_bias_array_address0),
    .ce0(dense_15_bias_array_ce0),
    .q0(dense_15_bias_array_q0)
);

k2c_dot_2 grp_k2c_dot_2_fu_192(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_k2c_dot_2_fu_192_ap_start),
    .ap_done(grp_k2c_dot_2_fu_192_ap_done),
    .ap_idle(grp_k2c_dot_2_fu_192_ap_idle),
    .ap_ready(grp_k2c_dot_2_fu_192_ap_ready),
    .C_array_address0(grp_k2c_dot_2_fu_192_C_array_address0),
    .C_array_ce0(grp_k2c_dot_2_fu_192_C_array_ce0),
    .C_array_we0(grp_k2c_dot_2_fu_192_C_array_we0),
    .C_array_d0(grp_k2c_dot_2_fu_192_C_array_d0),
    .C_array_q0(dense_15_output_arra_q0),
    .A_array_address0(grp_k2c_dot_2_fu_192_A_array_address0),
    .A_array_ce0(grp_k2c_dot_2_fu_192_A_array_ce0),
    .A_array_q0(dense_14_output_arra_q0),
    .A_dim(input_dim),
    .A_numel_read(input_numel_read),
    .B_dim(kernel_dim),
    .B_numel_read(dense_15_kernel_nume),
    .p_read2(tmp_16_reg_472)
);

k2c_affine_matmul_2 grp_k2c_affine_matmul_2_fu_216(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_k2c_affine_matmul_2_fu_216_ap_start),
    .ap_done(grp_k2c_affine_matmul_2_fu_216_ap_done),
    .ap_idle(grp_k2c_affine_matmul_2_fu_216_ap_idle),
    .ap_ready(grp_k2c_affine_matmul_2_fu_216_ap_ready),
    .C_address0(grp_k2c_affine_matmul_2_fu_216_C_address0),
    .C_ce0(grp_k2c_affine_matmul_2_fu_216_C_ce0),
    .C_we0(grp_k2c_affine_matmul_2_fu_216_C_we0),
    .C_d0(grp_k2c_affine_matmul_2_fu_216_C_d0),
    .C_q0(dense_15_output_arra_q0),
    .A_address0(grp_k2c_affine_matmul_2_fu_216_A_address0),
    .A_ce0(grp_k2c_affine_matmul_2_fu_216_A_ce0),
    .A_q0(dense_14_output_arra_q0),
    .B_address0(grp_k2c_affine_matmul_2_fu_216_B_address0),
    .B_ce0(grp_k2c_affine_matmul_2_fu_216_B_ce0),
    .B_q0(dense_15_kernel_arra_q0),
    .d_address0(grp_k2c_affine_matmul_2_fu_216_d_address0),
    .d_ce0(grp_k2c_affine_matmul_2_fu_216_d_ce0),
    .d_q0(dense_15_bias_array_q0),
    .outrows(p_s_reg_487)
);

sample_fadd_32ns_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sample_fadd_32ns_hbi_U127(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_238),
    .din1(dense_15_bias_array_1_reg_524),
    .ce(1'b1),
    .dout(grp_fu_229_p2)
);

sample_fcmp_32ns_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
sample_fcmp_32ns_ocq_U128(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_238),
    .din1(32'd0),
    .ce(1'b1),
    .opcode(5'd5),
    .dout(grp_fu_233_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_k2c_affine_matmul_2_fu_216_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (tmp_fu_244_p2 == 1'd1))) begin
            grp_k2c_affine_matmul_2_fu_216_ap_start_reg <= 1'b1;
        end else if ((grp_k2c_affine_matmul_2_fu_216_ap_ready == 1'b1)) begin
            grp_k2c_affine_matmul_2_fu_216_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_k2c_dot_2_fu_192_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (tmp_fu_244_p2 == 1'd0))) begin
            grp_k2c_dot_2_fu_192_ap_start_reg <= 1'b1;
        end else if ((grp_k2c_dot_2_fu_192_ap_ready == 1'b1)) begin
            grp_k2c_dot_2_fu_192_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (tmp_i_fu_291_p2 == 1'd0))) begin
        i_2_reg_169 <= 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        i_2_reg_169 <= i_34_reg_537;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (exitcond_i_fu_300_p2 == 1'd1))) begin
        i_i_reg_145 <= i_31_fu_326_p2;
    end else if (((1'b1 == ap_CS_fsm_state2) & (grp_k2c_dot_2_fu_192_ap_done == 1'b1))) begin
        i_i_reg_145 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_k2c_affine_matmul_2_fu_216_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        i_reg_181 <= 10'd0;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        i_reg_181 <= i_33_reg_573;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (tmp_i_fu_291_p2 == 1'd1))) begin
        j_i_reg_157 <= 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        j_i_reg_157 <= j_reg_504;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        dense_15_bias_array_1_reg_524 <= dense_15_bias_array_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state22) & (exitcond1_fu_397_p2 == 1'd0))) begin
        dense_15_output_arra_1_reg_578 <= i_cast1_fu_388_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (exitcond_i_fu_300_p2 == 1'd0))) begin
        dense_15_output_arra_4_reg_514 <= sum_i_cast_fu_321_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state16) & (exitcond4_fu_331_p2 == 1'd0) & (tmp_reg_468 == 1'd0))) begin
        dense_15_output_arra_6_reg_542 <= i_2_reg_169;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        i_33_reg_573 <= i_33_fu_402_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state16) & (tmp_reg_468 == 1'd0))) begin
        i_34_reg_537 <= i_34_fu_336_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (tmp_fu_244_p2 == 1'd1))) begin
        icmp_reg_482 <= icmp_fu_272_p2;
        p_s_reg_487[0] <= p_s_fu_278_p3[0];
p_s_reg_487[5] <= p_s_fu_278_p3[5];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        j_reg_504 <= j_fu_305_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        notlhs3_reg_583 <= notlhs3_fu_426_p2;
        notrhs4_reg_588 <= notrhs4_fu_432_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        notlhs_reg_547 <= notlhs_fu_360_p2;
        notrhs_reg_552 <= notrhs_fu_366_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state5))) begin
        reg_238 <= dense_15_output_arra_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (tmp_fu_244_p2 == 1'd0))) begin
        tmp_16_reg_472 <= tmp_16_fu_250_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_k2c_affine_matmul_2_fu_216_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        tmp_19_cast_cast_reg_565[4] <= tmp_19_cast_cast_fu_381_p3[4];
tmp_19_cast_cast_reg_565[9] <= tmp_19_cast_cast_fu_381_p3[9];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        tmp_19_reg_593 <= grp_fu_233_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        tmp_23_reg_557 <= grp_fu_233_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        tmp_i_15_reg_529 <= grp_fu_229_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_reg_468 <= tmp_fu_244_p2;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state16) & ((exitcond4_fu_331_p2 == 1'd1) | (tmp_reg_468 == 1'd1))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) & ((exitcond4_fu_331_p2 == 1'd1) | (tmp_reg_468 == 1'd1)))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        dense_14_output_arra_address0 = grp_k2c_affine_matmul_2_fu_216_A_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_14_output_arra_address0 = grp_k2c_dot_2_fu_192_A_array_address0;
    end else begin
        dense_14_output_arra_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        dense_14_output_arra_ce0 = grp_k2c_affine_matmul_2_fu_216_A_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_14_output_arra_ce0 = grp_k2c_dot_2_fu_192_A_array_ce0;
    end else begin
        dense_14_output_arra_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_15_bias_array_address0 = j_i_reg_157;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        dense_15_bias_array_address0 = grp_k2c_affine_matmul_2_fu_216_d_address0;
    end else begin
        dense_15_bias_array_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_15_bias_array_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        dense_15_bias_array_ce0 = grp_k2c_affine_matmul_2_fu_216_d_ce0;
    end else begin
        dense_15_bias_array_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        dense_15_kernel_arra_address0 = grp_k2c_affine_matmul_2_fu_216_B_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_15_kernel_arra_address0 = 9'd0;
    end else begin
        dense_15_kernel_arra_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        dense_15_kernel_arra_ce0 = grp_k2c_affine_matmul_2_fu_216_B_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_15_kernel_arra_ce0 = 1'b0;
    end else begin
        dense_15_kernel_arra_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        dense_15_output_arra_address0 = dense_15_output_arra_1_reg_578;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        dense_15_output_arra_address0 = i_cast1_fu_388_p1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        dense_15_output_arra_address0 = dense_15_output_arra_6_reg_542;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        dense_15_output_arra_address0 = i_2_reg_169;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        dense_15_output_arra_address0 = dense_15_output_arra_4_reg_514;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_15_output_arra_address0 = sum_i_cast_fu_321_p1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        dense_15_output_arra_address0 = grp_k2c_affine_matmul_2_fu_216_C_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_15_output_arra_address0 = grp_k2c_dot_2_fu_192_C_array_address0;
    end else begin
        dense_15_output_arra_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state4))) begin
        dense_15_output_arra_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        dense_15_output_arra_ce0 = grp_k2c_affine_matmul_2_fu_216_C_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_15_output_arra_ce0 = grp_k2c_dot_2_fu_192_C_array_ce0;
    end else begin
        dense_15_output_arra_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state20))) begin
        dense_15_output_arra_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        dense_15_output_arra_d0 = tmp_i_15_reg_529;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        dense_15_output_arra_d0 = grp_k2c_affine_matmul_2_fu_216_C_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_15_output_arra_d0 = grp_k2c_dot_2_fu_192_C_array_d0;
    end else begin
        dense_15_output_arra_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | ((1'b1 == ap_CS_fsm_state26) & (tmp_20_fu_442_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state20) & (tmp_24_fu_376_p2 == 1'd1)))) begin
        dense_15_output_arra_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        dense_15_output_arra_we0 = grp_k2c_affine_matmul_2_fu_216_C_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_15_output_arra_we0 = grp_k2c_dot_2_fu_192_C_array_we0;
    end else begin
        dense_15_output_arra_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (tmp_fu_244_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (tmp_fu_244_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_k2c_dot_2_fu_192_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (tmp_i_fu_291_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (exitcond_i_fu_300_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state16 : begin
            if (((1'b1 == ap_CS_fsm_state16) & ((exitcond4_fu_331_p2 == 1'd1) | (tmp_reg_468 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state21 : begin
            if (((grp_k2c_affine_matmul_2_fu_216_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            if (((1'b1 == ap_CS_fsm_state22) & (exitcond1_fu_397_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign dense_15_output_arra_3_fu_408_p1 = reg_238;

assign dense_15_output_arra_8_fu_342_p1 = reg_238;

assign exitcond1_fu_397_p2 = ((i_cast_fu_393_p1 == tmp_19_cast_cast_reg_565) ? 1'b1 : 1'b0);

assign exitcond4_fu_331_p2 = ((i_2_reg_169 == output_numel_read) ? 1'b1 : 1'b0);

assign exitcond_i_fu_300_p2 = ((j_i_reg_157 == dense_15_bias_numel) ? 1'b1 : 1'b0);

assign grp_k2c_affine_matmul_2_fu_216_ap_start = grp_k2c_affine_matmul_2_fu_216_ap_start_reg;

assign grp_k2c_dot_2_fu_192_ap_start = grp_k2c_dot_2_fu_192_ap_start_reg;

assign i_31_fu_326_p2 = (dense_15_bias_numel + i_i_reg_145);

assign i_33_fu_402_p2 = (i_reg_181 + 10'd1);

assign i_34_fu_336_p2 = (i_2_reg_169 + 64'd1);

assign i_cast1_fu_388_p1 = i_reg_181;

assign i_cast_fu_393_p1 = i_reg_181;

assign icmp_fu_272_p2 = ((tmp_61_fu_262_p4 != 63'd0) ? 1'b1 : 1'b0);

assign j_fu_305_p2 = (64'd1 + j_i_reg_157);

assign notlhs3_fu_426_p2 = ((tmp_s_fu_412_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notlhs_fu_360_p2 = ((tmp_21_fu_346_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notrhs4_fu_432_p2 = ((tmp_62_fu_422_p1 == 23'd0) ? 1'b1 : 1'b0);

assign notrhs_fu_366_p2 = ((tmp_65_fu_356_p1 == 23'd0) ? 1'b1 : 1'b0);

assign p_s_fu_278_p3 = ((icmp_fu_272_p2[0:0] === 1'b1) ? 6'd32 : 6'd1);

assign sum_i_cast_fu_321_p1 = sum_i_fu_315_p2;

assign sum_i_fu_315_p2 = (tmp_64_fu_311_p1 + tmp_63_fu_296_p1);

assign tmp_16_fu_250_p2 = ($signed(input_dim) + $signed(64'd18446744073709551615));

assign tmp_18_fu_438_p2 = (notrhs4_reg_588 | notlhs3_reg_583);

assign tmp_19_cast_cast_fu_381_p3 = ((icmp_reg_482[0:0] === 1'b1) ? 11'd512 : 11'd16);

assign tmp_20_fu_442_p2 = (tmp_19_reg_593 & tmp_18_fu_438_p2);

assign tmp_21_fu_346_p4 = {{dense_15_output_arra_8_fu_342_p1[30:23]}};

assign tmp_22_fu_372_p2 = (notrhs_reg_552 | notlhs_reg_547);

assign tmp_24_fu_376_p2 = (tmp_23_reg_557 & tmp_22_fu_372_p2);

assign tmp_61_fu_262_p4 = {{input_dim[63:1]}};

assign tmp_62_fu_422_p1 = dense_15_output_arra_3_fu_408_p1[22:0];

assign tmp_63_fu_296_p1 = j_i_reg_157[5:0];

assign tmp_64_fu_311_p1 = i_i_reg_145[5:0];

assign tmp_65_fu_356_p1 = dense_15_output_arra_8_fu_342_p1[22:0];

assign tmp_fu_244_p2 = ((input_dim < 64'd3) ? 1'b1 : 1'b0);

assign tmp_i_fu_291_p2 = ((i_i_reg_145 < output_numel_read) ? 1'b1 : 1'b0);

assign tmp_s_fu_412_p4 = {{dense_15_output_arra_3_fu_408_p1[30:23]}};

always @ (posedge ap_clk) begin
    p_s_reg_487[4:1] <= 4'b0000;
    tmp_19_cast_cast_reg_565[3:0] <= 4'b0000;
    tmp_19_cast_cast_reg_565[8:5] <= 4'b0000;
    tmp_19_cast_cast_reg_565[10] <= 1'b0;
end

endmodule //k2c_dense_1
